apiVersion: networkaddonsoperator.network.kubevirt.io/v1alpha1
kind: NetworkAddonsConfig
metadata:
  name: cluster
spec:
  multus:
    delegates: |
      [{
        "type": "flannel",
        "name": "cbr0",
        "delegate": {
          "isDefaultGateway": true
        }
      }]
  linuxBridge: {}
  kubeMacPool:
   endPoolRange: "FD:FF:FF:FF:FF:FF"
   startPoolRange: "02:00:00:00:00:00"
